# Generated by Django 5.1.3 on 2024-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_admintask_wasterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminTask',
        ),
        migrations.DeleteModel(
            name='WasteRequest',
        ),
    ]
