# Generated by Django 5.1.3 on 2024-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_admintask_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
